// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMadMDKyx3tdFQm9TRrrHZXoKVLEgcl6M',
    appId: '1:420774817607:web:f41e4a9e674d22a199a662',
    messagingSenderId: '420774817607',
    projectId: 'bookly-app-6eaae',
    authDomain: 'bookly-app-6eaae.firebaseapp.com',
    storageBucket: 'bookly-app-6eaae.appspot.com',
    measurementId: 'G-DJ5YW2YXQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTytDKlmYEs-ViIZ8AuPpW4bqbnPsRgvw',
    appId: '1:420774817607:android:b89460bb0e40b32999a662',
    messagingSenderId: '420774817607',
    projectId: 'bookly-app-6eaae',
    storageBucket: 'bookly-app-6eaae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGkiQ2jdRewjRa0G8jg_2XmciYdHNtBY',
    appId: '1:420774817607:ios:35832a37f7c22afc99a662',
    messagingSenderId: '420774817607',
    projectId: 'bookly-app-6eaae',
    storageBucket: 'bookly-app-6eaae.appspot.com',
    iosClientId: '420774817607-0kst31rkh2ihocdnpn935farmah1snpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoGkiQ2jdRewjRa0G8jg_2XmciYdHNtBY',
    appId: '1:420774817607:ios:35832a37f7c22afc99a662',
    messagingSenderId: '420774817607',
    projectId: 'bookly-app-6eaae',
    storageBucket: 'bookly-app-6eaae.appspot.com',
    iosClientId: '420774817607-0kst31rkh2ihocdnpn935farmah1snpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklyApp',
  );
}
